name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up Ansible
        uses: dawidd6/action-ansible@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Push Docker image
        run: |
          docker tag myapp:latest myregistry/myapp:latest
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login myregistry -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push myregistry/myapp:latest

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: dawidd6/action-ansible@v2

      - name: Run Tests
        run: ansible-playbook playbooks/test.yml

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: dawidd6/action-ansible@v2

      - name: Deploy
        run: ansible-playbook playbooks/deploy.yml --limit production
